name: Website Title
title: Website Title
author: Author Name
description: My personal web site.
url: https://account.github.io
timezone: Region/YourCity
permalink: /blog/:year/:month/:day/:title:output_ext
highlighter: rouge
email: your@email
github: account
markdown: kramdown
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-seo-tag
excerpt_separator: <!-- end-of-lead -->
collections:
  projects:
    output: true
    title: Projects
    permalink: /:collection/:name/
exclude:
  - README.md
  - docs
  - Gemfile
  - Gemfile.lock
  - "*~"
  - ".#*"
  - vendor
jekyll_compose:
  default_front_matter:
    drafts:
      layout: post
      author: Author Name
      email: your@email
      category:
      tags:
    posts:
      layout: post
      author: Author Name
      email: your@email
      category:
      tags:
    projects:
      layout: project
      title:
      name:
      link:
      short:
      author: Author Name
      date:
      status:
